using System.Collections.Generic;
using System.Linq;
using DevStackShared.AvailableVersions.Models;

namespace DevStackShared.AvailableVersions.Providers
{
    /// <summary>
    /// Provedor de versões disponíveis para Composer
    /// </summary>
    public class ComposerVersionProvider : IVersionProvider
    {
        public string ComponentName => "Composer";
        public string ComponentId => "composer";
        
        private static readonly List<VersionInfo> _versions = new List<VersionInfo>
        {
            new VersionInfo("1.0.0", "https://getcomposer.org/download/1.0.0/composer.phar"),
            new VersionInfo("1.0.1", "https://getcomposer.org/download/1.0.1/composer.phar"),
            new VersionInfo("1.0.2", "https://getcomposer.org/download/1.0.2/composer.phar"),
            new VersionInfo("1.0.3", "https://getcomposer.org/download/1.0.3/composer.phar"),
            new VersionInfo("1.1.0", "https://getcomposer.org/download/1.1.0/composer.phar"),
            new VersionInfo("1.1.1", "https://getcomposer.org/download/1.1.1/composer.phar"),
            new VersionInfo("1.1.2", "https://getcomposer.org/download/1.1.2/composer.phar"),
            new VersionInfo("1.1.3", "https://getcomposer.org/download/1.1.3/composer.phar"),
            new VersionInfo("1.2.0", "https://getcomposer.org/download/1.2.0/composer.phar"),
            new VersionInfo("1.2.1", "https://getcomposer.org/download/1.2.1/composer.phar"),
            new VersionInfo("1.2.2", "https://getcomposer.org/download/1.2.2/composer.phar"),
            new VersionInfo("1.2.3", "https://getcomposer.org/download/1.2.3/composer.phar"),
            new VersionInfo("1.2.4", "https://getcomposer.org/download/1.2.4/composer.phar"),
            new VersionInfo("1.3.0", "https://getcomposer.org/download/1.3.0/composer.phar"),
            new VersionInfo("1.3.1", "https://getcomposer.org/download/1.3.1/composer.phar"),
            new VersionInfo("1.3.2", "https://getcomposer.org/download/1.3.2/composer.phar"),
            new VersionInfo("1.3.3", "https://getcomposer.org/download/1.3.3/composer.phar"),
            new VersionInfo("1.4.0", "https://getcomposer.org/download/1.4.0/composer.phar"),
            new VersionInfo("1.4.1", "https://getcomposer.org/download/1.4.1/composer.phar"),
            new VersionInfo("1.4.2", "https://getcomposer.org/download/1.4.2/composer.phar"),
            new VersionInfo("1.4.3", "https://getcomposer.org/download/1.4.3/composer.phar"),
            new VersionInfo("1.5.0", "https://getcomposer.org/download/1.5.0/composer.phar"),
            new VersionInfo("1.5.1", "https://getcomposer.org/download/1.5.1/composer.phar"),
            new VersionInfo("1.5.2", "https://getcomposer.org/download/1.5.2/composer.phar"),
            new VersionInfo("1.5.3", "https://getcomposer.org/download/1.5.3/composer.phar"),
            new VersionInfo("1.5.4", "https://getcomposer.org/download/1.5.4/composer.phar"),
            new VersionInfo("1.5.5", "https://getcomposer.org/download/1.5.5/composer.phar"),
            new VersionInfo("1.5.6", "https://getcomposer.org/download/1.5.6/composer.phar"),
            new VersionInfo("1.6.0", "https://getcomposer.org/download/1.6.0/composer.phar"),
            new VersionInfo("1.6.1", "https://getcomposer.org/download/1.6.1/composer.phar"),
            new VersionInfo("1.6.2", "https://getcomposer.org/download/1.6.2/composer.phar"),
            new VersionInfo("1.6.3", "https://getcomposer.org/download/1.6.3/composer.phar"),
            new VersionInfo("1.6.4", "https://getcomposer.org/download/1.6.4/composer.phar"),
            new VersionInfo("1.6.5", "https://getcomposer.org/download/1.6.5/composer.phar"),
            new VersionInfo("1.7.0", "https://getcomposer.org/download/1.7.0/composer.phar"),
            new VersionInfo("1.7.1", "https://getcomposer.org/download/1.7.1/composer.phar"),
            new VersionInfo("1.7.2", "https://getcomposer.org/download/1.7.2/composer.phar"),
            new VersionInfo("1.7.3", "https://getcomposer.org/download/1.7.3/composer.phar"),
            new VersionInfo("1.8.0", "https://getcomposer.org/download/1.8.0/composer.phar"),
            new VersionInfo("1.8.1", "https://getcomposer.org/download/1.8.1/composer.phar"),
            new VersionInfo("1.8.2", "https://getcomposer.org/download/1.8.2/composer.phar"),
            new VersionInfo("1.8.3", "https://getcomposer.org/download/1.8.3/composer.phar"),
            new VersionInfo("1.8.4", "https://getcomposer.org/download/1.8.4/composer.phar"),
            new VersionInfo("1.8.5", "https://getcomposer.org/download/1.8.5/composer.phar"),
            new VersionInfo("1.8.6", "https://getcomposer.org/download/1.8.6/composer.phar"),
            new VersionInfo("1.9.0", "https://getcomposer.org/download/1.9.0/composer.phar"),
            new VersionInfo("1.9.1", "https://getcomposer.org/download/1.9.1/composer.phar"),
            new VersionInfo("1.9.2", "https://getcomposer.org/download/1.9.2/composer.phar"),
            new VersionInfo("1.9.3", "https://getcomposer.org/download/1.9.3/composer.phar"),
            new VersionInfo("1.10.0", "https://getcomposer.org/download/1.10.0/composer.phar"),
            new VersionInfo("1.10.1", "https://getcomposer.org/download/1.10.1/composer.phar"),
            new VersionInfo("1.10.2", "https://getcomposer.org/download/1.10.2/composer.phar"),
            new VersionInfo("1.10.3", "https://getcomposer.org/download/1.10.3/composer.phar"),
            new VersionInfo("1.10.4", "https://getcomposer.org/download/1.10.4/composer.phar"),
            new VersionInfo("1.10.5", "https://getcomposer.org/download/1.10.5/composer.phar"),
            new VersionInfo("1.10.6", "https://getcomposer.org/download/1.10.6/composer.phar"),
            new VersionInfo("1.10.7", "https://getcomposer.org/download/1.10.7/composer.phar"),
            new VersionInfo("1.10.8", "https://getcomposer.org/download/1.10.8/composer.phar"),
            new VersionInfo("1.10.9", "https://getcomposer.org/download/1.10.9/composer.phar"),
            new VersionInfo("1.10.10", "https://getcomposer.org/download/1.10.10/composer.phar"),
            new VersionInfo("1.10.11", "https://getcomposer.org/download/1.10.11/composer.phar"),
            new VersionInfo("1.10.12", "https://getcomposer.org/download/1.10.12/composer.phar"),
            new VersionInfo("1.10.13", "https://getcomposer.org/download/1.10.13/composer.phar"),
            new VersionInfo("1.10.14", "https://getcomposer.org/download/1.10.14/composer.phar"),
            new VersionInfo("1.10.15", "https://getcomposer.org/download/1.10.15/composer.phar"),
            new VersionInfo("1.10.16", "https://getcomposer.org/download/1.10.16/composer.phar"),
            new VersionInfo("1.10.17", "https://getcomposer.org/download/1.10.17/composer.phar"),
            new VersionInfo("1.10.18", "https://getcomposer.org/download/1.10.18/composer.phar"),
            new VersionInfo("1.10.19", "https://getcomposer.org/download/1.10.19/composer.phar"),
            new VersionInfo("1.10.20", "https://getcomposer.org/download/1.10.20/composer.phar"),
            new VersionInfo("1.10.21", "https://getcomposer.org/download/1.10.21/composer.phar"),
            new VersionInfo("1.10.22", "https://getcomposer.org/download/1.10.22/composer.phar"),
            new VersionInfo("1.10.23", "https://getcomposer.org/download/1.10.23/composer.phar"),
            new VersionInfo("1.10.24", "https://getcomposer.org/download/1.10.24/composer.phar"),
            new VersionInfo("1.10.25", "https://getcomposer.org/download/1.10.25/composer.phar"),
            new VersionInfo("1.10.26", "https://getcomposer.org/download/1.10.26/composer.phar"),
            new VersionInfo("1.10.27", "https://getcomposer.org/download/1.10.27/composer.phar"),
            new VersionInfo("2.0.0", "https://getcomposer.org/download/2.0.0/composer.phar"),
            new VersionInfo("2.0.1", "https://getcomposer.org/download/2.0.1/composer.phar"),
            new VersionInfo("2.0.2", "https://getcomposer.org/download/2.0.2/composer.phar"),
            new VersionInfo("2.0.3", "https://getcomposer.org/download/2.0.3/composer.phar"),
            new VersionInfo("2.0.4", "https://getcomposer.org/download/2.0.4/composer.phar"),
            new VersionInfo("2.0.5", "https://getcomposer.org/download/2.0.5/composer.phar"),
            new VersionInfo("2.0.6", "https://getcomposer.org/download/2.0.6/composer.phar"),
            new VersionInfo("2.0.7", "https://getcomposer.org/download/2.0.7/composer.phar"),
            new VersionInfo("2.0.8", "https://getcomposer.org/download/2.0.8/composer.phar"),
            new VersionInfo("2.0.9", "https://getcomposer.org/download/2.0.9/composer.phar"),
            new VersionInfo("2.0.10", "https://getcomposer.org/download/2.0.10/composer.phar"),
            new VersionInfo("2.0.11", "https://getcomposer.org/download/2.0.11/composer.phar"),
            new VersionInfo("2.0.12", "https://getcomposer.org/download/2.0.12/composer.phar"),
            new VersionInfo("2.0.13", "https://getcomposer.org/download/2.0.13/composer.phar"),
            new VersionInfo("2.0.14", "https://getcomposer.org/download/2.0.14/composer.phar"),
            new VersionInfo("2.1.0", "https://getcomposer.org/download/2.1.0/composer.phar"),
            new VersionInfo("2.1.1", "https://getcomposer.org/download/2.1.1/composer.phar"),
            new VersionInfo("2.1.2", "https://getcomposer.org/download/2.1.2/composer.phar"),
            new VersionInfo("2.1.3", "https://getcomposer.org/download/2.1.3/composer.phar"),
            new VersionInfo("2.1.4", "https://getcomposer.org/download/2.1.4/composer.phar"),
            new VersionInfo("2.1.5", "https://getcomposer.org/download/2.1.5/composer.phar"),
            new VersionInfo("2.1.6", "https://getcomposer.org/download/2.1.6/composer.phar"),
            new VersionInfo("2.1.7", "https://getcomposer.org/download/2.1.7/composer.phar"),
            new VersionInfo("2.1.8", "https://getcomposer.org/download/2.1.8/composer.phar"),
            new VersionInfo("2.1.9", "https://getcomposer.org/download/2.1.9/composer.phar"),
            new VersionInfo("2.1.10", "https://getcomposer.org/download/2.1.10/composer.phar"),
            new VersionInfo("2.1.11", "https://getcomposer.org/download/2.1.11/composer.phar"),
            new VersionInfo("2.1.12", "https://getcomposer.org/download/2.1.12/composer.phar"),
            new VersionInfo("2.1.14", "https://getcomposer.org/download/2.1.14/composer.phar"),
            new VersionInfo("2.2.0", "https://getcomposer.org/download/2.2.0/composer.phar"),
            new VersionInfo("2.2.1", "https://getcomposer.org/download/2.2.1/composer.phar"),
            new VersionInfo("2.2.2", "https://getcomposer.org/download/2.2.2/composer.phar"),
            new VersionInfo("2.2.3", "https://getcomposer.org/download/2.2.3/composer.phar"),
            new VersionInfo("2.2.4", "https://getcomposer.org/download/2.2.4/composer.phar"),
            new VersionInfo("2.2.5", "https://getcomposer.org/download/2.2.5/composer.phar"),
            new VersionInfo("2.2.6", "https://getcomposer.org/download/2.2.6/composer.phar"),
            new VersionInfo("2.2.7", "https://getcomposer.org/download/2.2.7/composer.phar"),
            new VersionInfo("2.2.8", "https://getcomposer.org/download/2.2.8/composer.phar"),
            new VersionInfo("2.2.9", "https://getcomposer.org/download/2.2.9/composer.phar"),
            new VersionInfo("2.2.10", "https://getcomposer.org/download/2.2.10/composer.phar"),
            new VersionInfo("2.2.11", "https://getcomposer.org/download/2.2.11/composer.phar"),
            new VersionInfo("2.2.12", "https://getcomposer.org/download/2.2.12/composer.phar"),
            new VersionInfo("2.2.13", "https://getcomposer.org/download/2.2.13/composer.phar"),
            new VersionInfo("2.2.14", "https://getcomposer.org/download/2.2.14/composer.phar"),
            new VersionInfo("2.2.15", "https://getcomposer.org/download/2.2.15/composer.phar"),
            new VersionInfo("2.2.16", "https://getcomposer.org/download/2.2.16/composer.phar"),
            new VersionInfo("2.2.17", "https://getcomposer.org/download/2.2.17/composer.phar"),
            new VersionInfo("2.2.18", "https://getcomposer.org/download/2.2.18/composer.phar"),
            new VersionInfo("2.2.19", "https://getcomposer.org/download/2.2.19/composer.phar"),
            new VersionInfo("2.2.20", "https://getcomposer.org/download/2.2.20/composer.phar"),
            new VersionInfo("2.2.21", "https://getcomposer.org/download/2.2.21/composer.phar"),
            new VersionInfo("2.2.22", "https://getcomposer.org/download/2.2.22/composer.phar"),
            new VersionInfo("2.2.23", "https://getcomposer.org/download/2.2.23/composer.phar"),
            new VersionInfo("2.2.24", "https://getcomposer.org/download/2.2.24/composer.phar"),
            new VersionInfo("2.2.25", "https://getcomposer.org/download/2.2.25/composer.phar"),
            new VersionInfo("2.3.0", "https://getcomposer.org/download/2.3.0/composer.phar"),
            new VersionInfo("2.3.1", "https://getcomposer.org/download/2.3.1/composer.phar"),
            new VersionInfo("2.3.2", "https://getcomposer.org/download/2.3.2/composer.phar"),
            new VersionInfo("2.3.3", "https://getcomposer.org/download/2.3.3/composer.phar"),
            new VersionInfo("2.3.4", "https://getcomposer.org/download/2.3.4/composer.phar"),
            new VersionInfo("2.3.5", "https://getcomposer.org/download/2.3.5/composer.phar"),
            new VersionInfo("2.3.6", "https://getcomposer.org/download/2.3.6/composer.phar"),
            new VersionInfo("2.3.7", "https://getcomposer.org/download/2.3.7/composer.phar"),
            new VersionInfo("2.3.8", "https://getcomposer.org/download/2.3.8/composer.phar"),
            new VersionInfo("2.3.9", "https://getcomposer.org/download/2.3.9/composer.phar"),
            new VersionInfo("2.3.10", "https://getcomposer.org/download/2.3.10/composer.phar"),
            new VersionInfo("2.4.0", "https://getcomposer.org/download/2.4.0/composer.phar"),
            new VersionInfo("2.4.1", "https://getcomposer.org/download/2.4.1/composer.phar"),
            new VersionInfo("2.4.2", "https://getcomposer.org/download/2.4.2/composer.phar"),
            new VersionInfo("2.4.3", "https://getcomposer.org/download/2.4.3/composer.phar"),
            new VersionInfo("2.4.4", "https://getcomposer.org/download/2.4.4/composer.phar"),
            new VersionInfo("2.5.0", "https://getcomposer.org/download/2.5.0/composer.phar"),
            new VersionInfo("2.5.1", "https://getcomposer.org/download/2.5.1/composer.phar"),
            new VersionInfo("2.5.2", "https://getcomposer.org/download/2.5.2/composer.phar"),
            new VersionInfo("2.5.3", "https://getcomposer.org/download/2.5.3/composer.phar"),
            new VersionInfo("2.5.4", "https://getcomposer.org/download/2.5.4/composer.phar"),
            new VersionInfo("2.5.5", "https://getcomposer.org/download/2.5.5/composer.phar"),
            new VersionInfo("2.5.6", "https://getcomposer.org/download/2.5.6/composer.phar"),
            new VersionInfo("2.5.7", "https://getcomposer.org/download/2.5.7/composer.phar"),
            new VersionInfo("2.5.8", "https://getcomposer.org/download/2.5.8/composer.phar"),
            new VersionInfo("2.6.0", "https://getcomposer.org/download/2.6.0/composer.phar"),
            new VersionInfo("2.6.1", "https://getcomposer.org/download/2.6.1/composer.phar"),
            new VersionInfo("2.6.2", "https://getcomposer.org/download/2.6.2/composer.phar"),
            new VersionInfo("2.6.3", "https://getcomposer.org/download/2.6.3/composer.phar"),
            new VersionInfo("2.6.4", "https://getcomposer.org/download/2.6.4/composer.phar"),
            new VersionInfo("2.6.5", "https://getcomposer.org/download/2.6.5/composer.phar"),
            new VersionInfo("2.6.6", "https://getcomposer.org/download/2.6.6/composer.phar"),
            new VersionInfo("2.7.0", "https://getcomposer.org/download/2.7.0/composer.phar"),
            new VersionInfo("2.7.1", "https://getcomposer.org/download/2.7.1/composer.phar"),
            new VersionInfo("2.7.2", "https://getcomposer.org/download/2.7.2/composer.phar"),
            new VersionInfo("2.7.3", "https://getcomposer.org/download/2.7.3/composer.phar"),
            new VersionInfo("2.7.4", "https://getcomposer.org/download/2.7.4/composer.phar"),
            new VersionInfo("2.7.5", "https://getcomposer.org/download/2.7.5/composer.phar"),
            new VersionInfo("2.7.6", "https://getcomposer.org/download/2.7.6/composer.phar"),
            new VersionInfo("2.7.7", "https://getcomposer.org/download/2.7.7/composer.phar"),
            new VersionInfo("2.7.8", "https://getcomposer.org/download/2.7.8/composer.phar"),
            new VersionInfo("2.7.9", "https://getcomposer.org/download/2.7.9/composer.phar"),
            new VersionInfo("2.8.0", "https://getcomposer.org/download/2.8.0/composer.phar"),
            new VersionInfo("2.8.1", "https://getcomposer.org/download/2.8.1/composer.phar"),
            new VersionInfo("2.8.2", "https://getcomposer.org/download/2.8.2/composer.phar"),
            new VersionInfo("2.8.3", "https://getcomposer.org/download/2.8.3/composer.phar"),
            new VersionInfo("2.8.4", "https://getcomposer.org/download/2.8.4/composer.phar"),
            new VersionInfo("2.8.5", "https://getcomposer.org/download/2.8.5/composer.phar"),
            new VersionInfo("2.8.6", "https://getcomposer.org/download/2.8.6/composer.phar"),
            new VersionInfo("2.8.7", "https://getcomposer.org/download/2.8.7/composer.phar"),
            new VersionInfo("2.8.8", "https://getcomposer.org/download/2.8.8/composer.phar"),
            new VersionInfo("2.8.9", "https://getcomposer.org/download/2.8.9/composer.phar"),
            new VersionInfo("2.8.10", "https://getcomposer.org/download/2.8.10/composer.phar"),
            new VersionInfo("2.8.11", "https://getcomposer.org/download/2.8.11/composer.phar"),
            new VersionInfo("2.8.12", "https://getcomposer.org/download/2.8.12/composer.phar")
        };
        
        public List<VersionInfo> GetAvailableVersions()
        {
            return new List<VersionInfo>(_versions);
        }
        
        public VersionInfo? GetLatestVersion()
        {
            return _versions.LastOrDefault();
        }
        
        public VersionInfo? GetVersion(string version)
        {
            return _versions.FirstOrDefault(v => v.Version == version);
        }
    }
}
