using System.Collections.Generic;
using System.Linq;
using DevStackShared.AvailableVersions.Models;

namespace DevStackShared.AvailableVersions.Providers
{
    /// <summary>
    /// Provedor de versões disponíveis para Elasticsearch
    /// </summary>
    public class ElasticsearchVersionProvider : IVersionProvider
    {
        public string ComponentName => "Elasticsearch";
        public string ComponentId => "elasticsearch";
        
        private static readonly List<VersionInfo> _versions = new List<VersionInfo>
        {
            new VersionInfo("7.2.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-windows-x86_64.zip"),
            new VersionInfo("7.2.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.1-windows-x86_64.zip"),
            new VersionInfo("7.3.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-windows-x86_64.zip"),
            new VersionInfo("7.3.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.1-windows-x86_64.zip"),
            new VersionInfo("7.3.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.2-windows-x86_64.zip"),
            new VersionInfo("7.4.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.0-windows-x86_64.zip"),
            new VersionInfo("7.4.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.1-windows-x86_64.zip"),
            new VersionInfo("7.4.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-windows-x86_64.zip"),
            new VersionInfo("7.5.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.0-windows-x86_64.zip"),
            new VersionInfo("7.5.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-windows-x86_64.zip"),
            new VersionInfo("7.5.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.2-windows-x86_64.zip"),
            new VersionInfo("7.6.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-windows-x86_64.zip"),
            new VersionInfo("7.6.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.1-windows-x86_64.zip"),
            new VersionInfo("7.6.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-windows-x86_64.zip"),
            new VersionInfo("7.7.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-windows-x86_64.zip"),
            new VersionInfo("7.7.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.1-windows-x86_64.zip"),
            new VersionInfo("7.8.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.0-windows-x86_64.zip"),
            new VersionInfo("7.8.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-windows-x86_64.zip"),
            new VersionInfo("7.9.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.0-windows-x86_64.zip"),
            new VersionInfo("7.9.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.1-windows-x86_64.zip"),
            new VersionInfo("7.9.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-windows-x86_64.zip"),
            new VersionInfo("7.9.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.3-windows-x86_64.zip"),
            new VersionInfo("7.10.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.0-windows-x86_64.zip"),
            new VersionInfo("7.10.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.1-windows-x86_64.zip"),
            new VersionInfo("7.10.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-windows-x86_64.zip"),
            new VersionInfo("7.11.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.11.0-windows-x86_64.zip"),
            new VersionInfo("7.11.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.11.1-windows-x86_64.zip"),
            new VersionInfo("7.11.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.11.2-windows-x86_64.zip"),
            new VersionInfo("7.12.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.0-windows-x86_64.zip"),
            new VersionInfo("7.12.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.1-windows-x86_64.zip"),
            new VersionInfo("7.13.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.0-windows-x86_64.zip"),
            new VersionInfo("7.13.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.1-windows-x86_64.zip"),
            new VersionInfo("7.13.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.2-windows-x86_64.zip"),
            new VersionInfo("7.13.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.3-windows-x86_64.zip"),
            new VersionInfo("7.13.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.4-windows-x86_64.zip"),
            new VersionInfo("7.14.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-windows-x86_64.zip"),
            new VersionInfo("7.14.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.1-windows-x86_64.zip"),
            new VersionInfo("7.14.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.2-windows-x86_64.zip"),
            new VersionInfo("7.15.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.0-windows-x86_64.zip"),
            new VersionInfo("7.15.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.1-windows-x86_64.zip"),
            new VersionInfo("7.15.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-windows-x86_64.zip"),
            new VersionInfo("7.16.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.0-windows-x86_64.zip"),
            new VersionInfo("7.16.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.1-windows-x86_64.zip"),
            new VersionInfo("7.16.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.2-windows-x86_64.zip"),
            new VersionInfo("7.16.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-windows-x86_64.zip"),
            new VersionInfo("7.17.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.0-windows-x86_64.zip"),
            new VersionInfo("7.17.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.1-windows-x86_64.zip"),
            new VersionInfo("7.17.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.2-windows-x86_64.zip"),
            new VersionInfo("7.17.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.3-windows-x86_64.zip"),
            new VersionInfo("7.17.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.4-windows-x86_64.zip"),
            new VersionInfo("7.17.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.5-windows-x86_64.zip"),
            new VersionInfo("7.17.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.6-windows-x86_64.zip"),
            new VersionInfo("7.17.7", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.7-windows-x86_64.zip"),
            new VersionInfo("7.17.8", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.8-windows-x86_64.zip"),
            new VersionInfo("7.17.9", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.9-windows-x86_64.zip"),
            new VersionInfo("7.17.10", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.10-windows-x86_64.zip"),
            new VersionInfo("7.17.11", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.11-windows-x86_64.zip"),
            new VersionInfo("7.17.12", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.12-windows-x86_64.zip"),
            new VersionInfo("7.17.13", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.13-windows-x86_64.zip"),
            new VersionInfo("7.17.14", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.14-windows-x86_64.zip"),
            new VersionInfo("7.17.15", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.15-windows-x86_64.zip"),
            new VersionInfo("7.17.16", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.16-windows-x86_64.zip"),
            new VersionInfo("7.17.17", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.17-windows-x86_64.zip"),
            new VersionInfo("7.17.18", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.18-windows-x86_64.zip"),
            new VersionInfo("7.17.19", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.19-windows-x86_64.zip"),
            new VersionInfo("7.17.20", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.20-windows-x86_64.zip"),
            new VersionInfo("7.17.21", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.21-windows-x86_64.zip"),
            new VersionInfo("7.17.22", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.22-windows-x86_64.zip"),
            new VersionInfo("7.17.23", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.23-windows-x86_64.zip"),
            new VersionInfo("7.17.24", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.24-windows-x86_64.zip"),
            new VersionInfo("7.17.25", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.25-windows-x86_64.zip"),
            new VersionInfo("7.17.26", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.26-windows-x86_64.zip"),
            new VersionInfo("7.17.27", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.27-windows-x86_64.zip"),
            new VersionInfo("7.17.28", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.28-windows-x86_64.zip"),
            new VersionInfo("7.17.29", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.29-windows-x86_64.zip"),
            new VersionInfo("8.0.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.0.0-windows-x86_64.zip"),
            new VersionInfo("8.0.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.0.1-windows-x86_64.zip"),
            new VersionInfo("8.1.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.1.0-windows-x86_64.zip"),
            new VersionInfo("8.1.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.1.1-windows-x86_64.zip"),
            new VersionInfo("8.1.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.1.2-windows-x86_64.zip"),
            new VersionInfo("8.1.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.1.3-windows-x86_64.zip"),
            new VersionInfo("8.2.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.2.0-windows-x86_64.zip"),
            new VersionInfo("8.2.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.2.1-windows-x86_64.zip"),
            new VersionInfo("8.2.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.2.2-windows-x86_64.zip"),
            new VersionInfo("8.2.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.2.3-windows-x86_64.zip"),
            new VersionInfo("8.3.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.3.0-windows-x86_64.zip"),
            new VersionInfo("8.3.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.3.1-windows-x86_64.zip"),
            new VersionInfo("8.3.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.3.2-windows-x86_64.zip"),
            new VersionInfo("8.3.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.3.3-windows-x86_64.zip"),
            new VersionInfo("8.4.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.0-windows-x86_64.zip"),
            new VersionInfo("8.4.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.1-windows-x86_64.zip"),
            new VersionInfo("8.4.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.2-windows-x86_64.zip"),
            new VersionInfo("8.4.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.4.3-windows-x86_64.zip"),
            new VersionInfo("8.5.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.0-windows-x86_64.zip"),
            new VersionInfo("8.5.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.1-windows-x86_64.zip"),
            new VersionInfo("8.5.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.2-windows-x86_64.zip"),
            new VersionInfo("8.5.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.3-windows-x86_64.zip"),
            new VersionInfo("8.6.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.0-windows-x86_64.zip"),
            new VersionInfo("8.6.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.1-windows-x86_64.zip"),
            new VersionInfo("8.6.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.2-windows-x86_64.zip"),
            new VersionInfo("8.7.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.7.0-windows-x86_64.zip"),
            new VersionInfo("8.7.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.7.1-windows-x86_64.zip"),
            new VersionInfo("8.8.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.0-windows-x86_64.zip"),
            new VersionInfo("8.8.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.1-windows-x86_64.zip"),
            new VersionInfo("8.8.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.2-windows-x86_64.zip"),
            new VersionInfo("8.9.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.9.0-windows-x86_64.zip"),
            new VersionInfo("8.9.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.9.1-windows-x86_64.zip"),
            new VersionInfo("8.9.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.9.2-windows-x86_64.zip"),
            new VersionInfo("8.10.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.0-windows-x86_64.zip"),
            new VersionInfo("8.10.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.1-windows-x86_64.zip"),
            new VersionInfo("8.10.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.2-windows-x86_64.zip"),
            new VersionInfo("8.10.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.3-windows-x86_64.zip"),
            new VersionInfo("8.10.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.4-windows-x86_64.zip"),
            new VersionInfo("8.11.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.0-windows-x86_64.zip"),
            new VersionInfo("8.11.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.1-windows-x86_64.zip"),
            new VersionInfo("8.11.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.2-windows-x86_64.zip"),
            new VersionInfo("8.11.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-windows-x86_64.zip"),
            new VersionInfo("8.11.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.4-windows-x86_64.zip"),
            new VersionInfo("8.12.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.12.0-windows-x86_64.zip"),
            new VersionInfo("8.12.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.12.1-windows-x86_64.zip"),
            new VersionInfo("8.12.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.12.2-windows-x86_64.zip"),
            new VersionInfo("8.13.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.0-windows-x86_64.zip"),
            new VersionInfo("8.13.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.1-windows-x86_64.zip"),
            new VersionInfo("8.13.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.2-windows-x86_64.zip"),
            new VersionInfo("8.13.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.3-windows-x86_64.zip"),
            new VersionInfo("8.13.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.4-windows-x86_64.zip"),
            new VersionInfo("8.14.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.14.0-windows-x86_64.zip"),
            new VersionInfo("8.14.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.14.1-windows-x86_64.zip"),
            new VersionInfo("8.14.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.14.3-windows-x86_64.zip"),
            new VersionInfo("8.15.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-windows-x86_64.zip"),
            new VersionInfo("8.15.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.1-windows-x86_64.zip"),
            new VersionInfo("8.15.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.2-windows-x86_64.zip"),
            new VersionInfo("8.15.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.3-windows-x86_64.zip"),
            new VersionInfo("8.15.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.4-windows-x86_64.zip"),
            new VersionInfo("8.15.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.5-windows-x86_64.zip"),
            new VersionInfo("8.16.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.0-windows-x86_64.zip"),
            new VersionInfo("8.16.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.1-windows-x86_64.zip"),
            new VersionInfo("8.16.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.2-windows-x86_64.zip"),
            new VersionInfo("8.16.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.3-windows-x86_64.zip"),
            new VersionInfo("8.16.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.4-windows-x86_64.zip"),
            new VersionInfo("8.16.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.5-windows-x86_64.zip"),
            new VersionInfo("8.16.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.16.6-windows-x86_64.zip"),
            new VersionInfo("8.17.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.0-windows-x86_64.zip"),
            new VersionInfo("8.17.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.1-windows-x86_64.zip"),
            new VersionInfo("8.17.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.2-windows-x86_64.zip"),
            new VersionInfo("8.17.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.3-windows-x86_64.zip"),
            new VersionInfo("8.17.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.4-windows-x86_64.zip"),
            new VersionInfo("8.17.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.5-windows-x86_64.zip"),
            new VersionInfo("8.17.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.6-windows-x86_64.zip"),
            new VersionInfo("8.17.7", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.7-windows-x86_64.zip"),
            new VersionInfo("8.17.8", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.8-windows-x86_64.zip"),
            new VersionInfo("8.17.9", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.9-windows-x86_64.zip"),
            new VersionInfo("8.17.10", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.17.10-windows-x86_64.zip"),
            new VersionInfo("8.18.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.0-windows-x86_64.zip"),
            new VersionInfo("8.18.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.1-windows-x86_64.zip"),
            new VersionInfo("8.18.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.2-windows-x86_64.zip"),
            new VersionInfo("8.18.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.3-windows-x86_64.zip"),
            new VersionInfo("8.18.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.4-windows-x86_64.zip"),
            new VersionInfo("8.18.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.5-windows-x86_64.zip"),
            new VersionInfo("8.18.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.6-windows-x86_64.zip"),
            new VersionInfo("8.18.7", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.7-windows-x86_64.zip"),
            new VersionInfo("8.18.8", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.18.8-windows-x86_64.zip"),
            new VersionInfo("8.19.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.0-windows-x86_64.zip"),
            new VersionInfo("8.19.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.1-windows-x86_64.zip"),
            new VersionInfo("8.19.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.2-windows-x86_64.zip"),
            new VersionInfo("8.19.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.3-windows-x86_64.zip"),
            new VersionInfo("8.19.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.4-windows-x86_64.zip"),
            new VersionInfo("8.19.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.5-windows-x86_64.zip"),
            new VersionInfo("8.19.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.19.6-windows-x86_64.zip"),
            new VersionInfo("9.0.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.0-windows-x86_64.zip"),
            new VersionInfo("9.0.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.1-windows-x86_64.zip"),
            new VersionInfo("9.0.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.2-windows-x86_64.zip"),
            new VersionInfo("9.0.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.3-windows-x86_64.zip"),
            new VersionInfo("9.0.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.4-windows-x86_64.zip"),
            new VersionInfo("9.0.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.5-windows-x86_64.zip"),
            new VersionInfo("9.0.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.6-windows-x86_64.zip"),
            new VersionInfo("9.0.7", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.7-windows-x86_64.zip"),
            new VersionInfo("9.0.8", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.8-windows-x86_64.zip"),
            new VersionInfo("9.1.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.0-windows-x86_64.zip"),
            new VersionInfo("9.1.1", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.1-windows-x86_64.zip"),
            new VersionInfo("9.1.2", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.2-windows-x86_64.zip"),
            new VersionInfo("9.1.3", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.3-windows-x86_64.zip"),
            new VersionInfo("9.1.4", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.4-windows-x86_64.zip"),
            new VersionInfo("9.1.5", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.5-windows-x86_64.zip"),
            new VersionInfo("9.1.6", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.1.6-windows-x86_64.zip"),
            new VersionInfo("9.2.0", "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.2.0-windows-x86_64.zip")
        };
        
        public List<VersionInfo> GetAvailableVersions()
        {
            return new List<VersionInfo>(_versions);
        }
        
        public VersionInfo? GetLatestVersion()
        {
            return _versions.LastOrDefault();
        }
        
        public VersionInfo? GetVersion(string version)
        {
            return _versions.FirstOrDefault(v => v.Version == version);
        }
    }
}
